# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      tailwind-daisyui:
        patterns: 
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "autoprefixer"
          - "daisyui"
        update-types:
          - "minor"
      vite-vue-ts:
        patterns:
          - "vue"
          - "@vue/*"
          - "vue-router"
          - "typescript"
          - "vue-tsc"
          - "vite"
          - "@vitejs/*"
          - "vite-plugin-pwa"
          - "@types/*"
          - "@tsconfig/node20"
          - "prettier"
          - "@rushstack/eslint-patch"
          - "eslint"
          - "eslint-plugin-vue"
          - "npm-run-all2"
        update-types:
          - "minor"
      application:
        patterns:
          - "openpgp"
          - "@openpgp/*"
          - "html5-qrcode"
        update-types:
          - "minor"
